name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    ## checks out our project source code
    - uses: actions/checkout@v2
    
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lllamnyp/consensus-backend:$(date +%s)

    ## Publishes our image to Docker Hub 😎
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      pre: echo ::save-state name=IMAGE_TAG::$(echo $(date +%s))
      with:
        ## the name of our image
        name: lllamnyp/consensus-backend
        ## Here we pass in our Docker Username
        username: ${{ secrets.DOCKER_USERNAME }}
        ## and our Docker password which 
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.STATE_IMAGE_TAG }}"
